version: '3'
services:
  monitoring:
    image: 'jan1993/system_sensors:arm32v7'
    restart: always
    container_name: system-sensors
    devices:
      - /dev/vchiq
    volumes:
      - /opt/vc:/opt/vc
    environment:
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - MQTT_USERNAME=my_user
      - MQTT_PASSWORD=my_password
      - DEVICE_NAME=myPi
      - LD_LIBRARY_PATH=/opt/vc/lib
